demos:
  root: demo/src/commonMain/kotlin/com/composables/ui/demo/examples
  files:
    alert-dialog: AlertDialogExample.kt
    alert-dialog-3-actions: AlertDialogThreeActionsExample.kt
    alert-dialog-icon: AlertDialogWithIconExample.kt
    bottom-sheet-action-menu: BottomSheetActionMenuExample.kt
    bottom-sheet-confirmation: BottomSheetConfirmationExample.kt
    bottom-sheet-form: BottomSheetFormExample.kt
    button-default: ButtonExample.kt
    button-disabled: DisabledButtonExample.kt
    button-sizes: ButtonSizesExample.kt
    button-primary: PrimaryButtonExample.kt
    button-secondary: SecondaryButtonExample.kt
    button-outlined: OutlinedButtonExample.kt
    button-ghost: GhostButtonExample.kt
    button-destructive: DestructiveButtonExample.kt
    checkbox: CheckboxExample.kt
    checkbox-disabled: DisabledCheckboxExample.kt
    checkbox-tri-state: TriStateCheckboxExample.kt
    checkbox-tri-state-disabled: DisabledTriStateCheckboxExample.kt
    disclosure: DisclosureExample.kt
    disclosure-indicator: DisclosureWithIndicatorExample.kt
    disclosure-disabled: DisabledDisclosureExample.kt
    dropdown-menu: DropdownMenuExample.kt
    dropdown-menu-toolbar: DropdownMenuToolbarExample.kt
    icon: IconExample.kt
    icon-tinted: TintedIconExample.kt
    icon-themed: ThemedIconExample.kt
    navigation-bar: NavigationBarExample.kt
    disabled-navigation-bar: DisabledNavigationBarExample.kt
    custom-insets-navigation-bar: CustomInsetsNavigationBarExample.kt
    progress-indicator: ProgressIndicatorExample.kt
    progress-indicator-indeterminate: IndeterminateProgressIndicatorExample.kt
    radio-group: RadioGroupExample.kt
    radio-group-disabled: DisabledRadioGroupExample.kt
    scrollbars-vertical: ScrollbarExample.kt
    scrollbars-horizontal: HorizontalScrollbarExample.kt
    scrollbars-lazy-column: LazyColumnScrollbarExample.kt
    scrollbars-always-visible: AlwaysVisibleScrollbarExample.kt
    scrollbars-vertical-disabled: DisabledScrollbarExample.kt
    scrollbars-horizontal-disabled: DisabledHorizontalScrollbarExample.kt
    separators-horizontal: SeparatorsExample.kt
    separators-vertical: VerticalSeparatorExample.kt
    slider: SliderExample.kt
    slider-vertical: VerticalSliderExample.kt
    slider-disabled: DisabledSliderExample.kt
    slider-steps: SteppedSliderExample.kt
    tabs: TabsExample.kt
    tabs-weighted: WeightedTabsExample.kt
    tabs-icons: TabsWithIconsExample.kt
    tabs-vertical: VerticalTabsExample.kt
    tabs-disabled: DisabledTabsExample.kt
    text-field: DefaultTextFieldExample.kt
    text-field-ghost: GhostTextFieldExample.kt
    text-field-search: SearchTextFieldExample.kt
    text-field-multiline: MultilineTextFieldExample.kt
    text-field-disabled: DisabledTextFieldExample.kt
    text-field-read-only: ReadOnlyTextFieldExample.kt
    text: TextExample.kt
    text-styled: StyledTextExample.kt
    text-themed: ThemedTextExample.kt
    switch: SwitchExample.kt
    switch-disabled: DisabledSwitchExample.kt
    toolbar-actions: ToolbarWithActionsExample.kt
    centered-toolbar: CenteredToolbarExample.kt
    large-toolbar: LargeToolbarExample.kt
    tooltip: TooltipExample.kt
    tooltip-side: TooltipSideExample.kt
    tooltip-alignment: TooltipAlignmentExample.kt
    tooltip-hover-delay: TooltipHoverDelayExample.kt
    tooltip-long-press-duration: TooltipLongPressDurationExample.kt

components:
  root: ui/src/commonMain/kotlin/com/composables/ui
  files:
    components/AlertDialog.kt: components/AlertDialog.kt
    components/BottomSheet.kt: components/BottomSheet.kt
    components/Button.kt: components/Button.kt
    components/Checkbox.kt: components/Checkbox.kt
    components/Disclosure.kt: components/Disclosure.kt
    components/DropdownMenu.kt: components/DropdownMenu.kt
    components/Icon.kt: components/Icon.kt
    components/NavigationBar.kt: components/NavigationBar.kt
    components/Progress.kt: components/Progress.kt
    components/RadioGroup.kt: components/RadioGroup.kt
    components/Scrollbars.kt: components/Scrollbars.kt
    components/Separators.kt: components/Separators.kt
    components/Slider.kt: components/Slider.kt
    components/Switch.kt: components/Switch.kt
    components/Tabs.kt: components/Tabs.kt
    components/Text.kt: components/Text.kt
    components/TextField.kt: components/TextField.kt
    components/Toolbar.kt: components/Toolbar.kt
    components/Tooltip.kt: components/Tooltip.kt
    components/TriStateCheckbox.kt: components/TriStateCheckbox.kt
    components/Utils.kt: components/Utils.kt
    theme/Theme.kt: theme/Theme.kt
